### ISSUE TITLE
incompatible with easy_localization_loader 2.0.0.

### ISSUE THREAD

**Issue by seanbabby** [rinlv/easy_localization_generator#15]
`flutter pub get`
`Resolving dependencies...`
```
Because easy_localization_generator >=0.3.0 depends on http ^0.13.5 and easy_localization_loader 2.0.0 depends on http ^1.0.0, easy_localization_generator >=0.3.0 is incompatible with easy_localization_loader 2.0.0.
And because no versions of easy_localization_loader match >2.0.0 <3.0.0, easy_localization_generator >=0.3.0 is incompatible with easy_localization_loader ^2.0.0.
```
`So, because example depends on both easy_localization_loader ^2.0.0 and easy_localization_generator ^0.3.1, version solving failed.`
`exit code 1`

incompatible with easy_localization_loader 2.0.0.
plan to udpate ?

**Comment by rinlv** [comment]
You can get the latest version. I resolved it.
Tips: you can use `dependency_overrides` to override the version of conflict packages.
